version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
  pre_build:
    commands:
      - echo Build started on `date`
      - go test
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - lambda
  name: go-lambda-example-$(+%Y%m%d.%H%M%s) 
